---
services:
  git:
    image: charmcli/soft-serve:v0.10
    networks: [web]
    ports: [23232:23232, 23233:23233, 9418:9418, 22:22]
    environment:
      - SOFT_SERVE_INITIAL_ADMIN_KEYS:${ADMIN_SSH_KEY}
      - SSH_FALLBACK:${ADMIN_SSH_KEY_FALLBACK}
    volumes: [./data:/soft-serve, ./config.yaml:/soft-serve/config.yaml]
    labels:
      - traefik.enable=true
      - traefik.http.routers.git.tls.certresolver=cloudflare
      - traefik.http.routers.git.rule=Host(`git.${DOMAIN}`) || Host(`git.${ALT_DOMAIN}`)
      - traefik.http.routers.git.tls.domains[0].main=git.${DOMAIN}
      - traefik.http.routers.git.tls.domains[1].main=git.${ALT_DOMAIN}
    restart: unless-stopped
