---
services:
  traeffik:
    image: traefik:v3.1
    container_name: traefik
    networks: [web]
    command: [--log.level=DEBUG]
    ports:
      - 443:443  # https
      - 80:80  # http
      - 8080:8080  # dashboard (LAN only, do not expose)
    environment:
      - CF_DNS_API_TOKEN=${CLOUDFLARE_TOKEN}
      - DOMAIN=${DOMAIN}
      - ALT_DOMAIN=${ALT_DOMAIN}
      - EMAIL=${EMAIL}
    extra_hosts: [host.docker.internal:host-gateway]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - ./traefik/certs:/var/traefik/certs:rw
    restart: unless-stopped
  site:
    extends:
      file: ./site/docker-compose.yml
      service: site
  git:
    extends:
      file: ./git/docker-compose.yml
      service: git
  dyndns:
    extends:
      file: ./dyndns/docker-compose.yml
      service: dyndns
networks:
  web:
