---
services:
  dyndns:
    image: favonia/cloudflare-ddns:1.15.1
    network_mode: host
    user: 1000:1000
    read_only: true
    cap_drop: [all]
    security_opt: ['no-new-privileges:true']
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_TOKEN}
      - DOMAINS=${DOMAIN},${ALT_DOMAIN}
      - PROXIED=false
    restart: unless-stopped
