---
services:
  vault:
    image: vaultwarden/server
    networks: [web]
    ports: [4242:80]
    volumes: [./data:/data]
    environment:
      DOMAIN: https://vault.${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.vault.tls.certresolver=cloudflare
      - traefik.http.routers.vault.rule=Host(`vault.${DOMAIN}`) || Host(`vault.${ALT_DOMAIN}`)
      - traefik.http.routers.vault.tls.domains[0].main=vault.${DOMAIN}
      - traefik.http.routers.vault.tls.domains[1].main=vault.${ALT_DOMAIN}
