---
services:
  vault:
    image: vaultwarden/server:1.34.3
    networks: [web]
    ports: [4242:80]
    volumes: [./data:/data]
    environment:
      DOMAIN: https://vault.${DOMAIN}
      SIGNUPS_ALLOWED: false
      YUBICO_CLIENT_ID: ${YUBICO_CLIENT_ID}
      YUBICO_SECRET_KEY: ${YUBICO_SECRET_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.vault.tls.certresolver=cloudflare
      - traefik.http.routers.vault.rule=Host(`vault.${DOMAIN}`) || Host(`vault.${ALT_DOMAIN}`)
      - traefik.http.routers.vault.tls.domains[0].main=vault.${DOMAIN}
      - traefik.http.routers.vault.tls.domains[1].main=vault.${ALT_DOMAIN}
    restart: unless-stopped
